Increase test coverage of the following Rules
Respect/Validation pull request #1457
Opened 2024-04-21 17:00 UTC by dcorrea777

- Base64
- Base
- Bsn
- Contains
- Executable
- FilterVar
- In
- Ip
- Isbn
- NoWhiteSpace
- Pesel
- Phone
- PolishIdCard
- PortugueseNif
- PublicDomainSuffix
- StartsWith
- Subset
- Version
- VideoUrl

2024-04-22 13:58 UTC, henriquemoody requested changes
Happy to see you here, @dcorrea777!

I've made a few suggestions removing the `->evaluate(...)`. That's because when we keep it, it's not clear that the exception is throw on a constructor level, in fact, it gives the impression that the exception is throw in the `evaluate()` method.

2024-04-22 13:58 UTC, henriquemoody commented on tests/unit/Rules/BaseTest.php
> +        (new Base(63))->evaluate('011010001');
```suggestion
        new Base(63);
```

2024-04-22 13:58 UTC, henriquemoody commented on tests/unit/Rules/PhoneTest.php
> +        (new Phone('BRR'))->evaluate('+1 11 91111 1111');
```suggestion
        new Phone('BRR');
```

2024-04-22 13:58 UTC, henriquemoody commented on tests/unit/Rules/VideoUrlTest.php
> +        (new VideoUrl('tiktok'))->evaluate('https://tiktok.com/video/71787467');
```suggestion
        new VideoUrl('tiktok');
```

2024-04-22 21:17 UTC, dcorrea777 commented
I was actually a bit unsure whether it was really necessary to call the evaluate method, but now it's clear to me. Thank for you reply @henriquemoody

2024-04-23 13:48 UTC, henriquemoody commented
The only thing I would change in your merge request is the commit message. The short message says, "Increase test coverage of the following Rules," but when you see that in the commit list, that doesn't make much sense because the following rules are not in the short message. In this case, I would just say, "Increase code coverage for some rules"

2024-04-23 13:59 UTC, henriquemoody commented
Merged by 2d90bc3484dc0739e5dab91e37b4067eecb22e60

Thank you for contributing, @dcorrea777!! 🐼

2024-04-23 13:59 UTC, closed without merging